### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by sawyerh** [atecarlos/webpack-babel-jest#12]
Not sure what the solution would be for this, but any chance of getting this to make Webpack code splitting to play nice with Jest? Right now things fail anywhere you use `require.ensure`:

```
TypeError: require.ensure is not a function
        at componentDidMount (app/assets/js/react/components/datetimepicker.jsx:16:13)
        at invokeComponentDidMountWithTimer (node_modules/react/lib/ReactCompositeComponent.js:63:18)
        at CallbackQueue._assign.notifyAll (node_modules/react/lib/CallbackQueue.js:66:22)
        at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (node_modules/react/lib/ReactReconcileTransaction.js:79:26)
        at ReactReconcileTransaction.Mixin.closeAll (node_modules/react/lib/Transaction.js:202:25)
        at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:149:16)
        at batchedMountComponentIntoNode (node_modules/react/lib/ReactMount.js:123:15)
        at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
        at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
        at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:98:20)
        at Object.ReactMount._renderNewRootComponent (node_modules/react/lib/ReactMount.js:286:18)
        at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react/lib/ReactMount.js:365:32)
        at Object.ReactMount.render (node_modules/react/lib/ReactMount.js:386:23)
        at Object.ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:82:21)
        at Object.eval (app/assets/js/react/components/__tests__/datetimepicker-test.js:26:36)
        at Object.<anonymous> (node_modules/jest-jasmine2/src/jasmine-pit.js:35:32)
        at jasmine2 (node_modules/jest-jasmine2/src/index.js:253:7)
        at Test.run (node_modules/jest-cli/src/Test.js:44:12)
        at process._tickCallback (node.js:379:9)
```

Related: https://github.com/webpack/webpack/issues/183

**Comment by sawyerh** [comment]
At the moment this is what I'm doing to get around the error:

``` js
var babelJest = require('babel-jest');

module.exports = {
  process: function(src, filename) {
    var processed = babelJest.process(src, filename)
        .replace(/require\(\s*'[a-zA-Z0-9\/\._\-!]*\.(css|scss|less)'\);/gm, '');

    if (processed.match(/require\.ensure\(/) && !processed.match(/require\.ensure =/))
      processed += 'if(typeof require.ensure !== "function") require.ensure = function(d, c) { c(require) };';

    return processed;
  }
};
```

**Comment by atecarlos** [comment]
Hi @sawyerh I haven't used require.ensure in any of my projects yet, so I haven't run into this issue before. 

What I can suggest for the moment is to require('webpack-babel-jest') instead of 'babel-jest' and just working on top of that so that you at least you don't have to duplicate the stylesheets functionality.

How has this solution held up in the last few days?

**Comment by sawyerh** [comment]
@atecarlos Thanks for the tip! This has held up fine for me over the past few weeks.

**Comment by josephdonnelly** [comment]
I was having this issue too and solved it by using the transform-es2015-modules-commonjs plugin.

In my package.json:
```
"env": {
      "test": {
        "plugins": [
          "rewire",
          "transform-class-properties",
          "transform-es2015-modules-commonjs"
        ]
      }
    }
```

**Comment by josephdonnelly** [comment]
Was able to get around this by running this function before using require.ensure:
```
function checkRequire() {
  if (typeof require.ensure !== 'function') {
    require.ensure = function check(d, c) {
      c(require);
    };
  }
}
```
